// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "text$subexpression$1$ebnf$1", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$1", "symbols": ["word", "text$subexpression$1$ebnf$1", "_"]},
    {"name": "text$subexpression$1$ebnf$2", "symbols": ["digit"]},
    {"name": "text$subexpression$1$ebnf$2", "symbols": ["text$subexpression$1$ebnf$2", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "text$subexpression$1$ebnf$3", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$1", "symbols": ["text$subexpression$1$ebnf$2", "text$subexpression$1$ebnf$3", "_"]},
    {"name": "text", "symbols": ["text$subexpression$1"]},
    {"name": "text$subexpression$2$ebnf$1", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$2", "symbols": ["word", "text$subexpression$2$ebnf$1", "_"]},
    {"name": "text$subexpression$2$ebnf$2", "symbols": ["digit"]},
    {"name": "text$subexpression$2$ebnf$2", "symbols": ["text$subexpression$2$ebnf$2", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "text$subexpression$2$ebnf$3", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$2", "symbols": ["text$subexpression$2$ebnf$2", "text$subexpression$2$ebnf$3", "_"]},
    {"name": "text", "symbols": ["text", "text$subexpression$2"]},
    {"name": "words$ebnf$1", "symbols": ["word"]},
    {"name": "words$ebnf$1", "symbols": ["words$ebnf$1", "word"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "words", "symbols": ["words$ebnf$1"]},
    {"name": "word$ebnf$1", "symbols": ["letter"]},
    {"name": "word$ebnf$1", "symbols": ["word$ebnf$1", "letter"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "word", "symbols": ["word$ebnf$1"], "postprocess": (data) => data[0].join('')},
    {"name": "letter$subexpression$1", "symbols": ["A"]},
    {"name": "letter$subexpression$1", "symbols": ["B"]},
    {"name": "letter$subexpression$1", "symbols": ["C"]},
    {"name": "letter$subexpression$1", "symbols": ["D"]},
    {"name": "letter$subexpression$1", "symbols": ["E"]},
    {"name": "letter$subexpression$1", "symbols": ["F"]},
    {"name": "letter$subexpression$1", "symbols": ["G"]},
    {"name": "letter$subexpression$1", "symbols": ["H"]},
    {"name": "letter$subexpression$1", "symbols": ["I"]},
    {"name": "letter$subexpression$1", "symbols": ["J"]},
    {"name": "letter$subexpression$1", "symbols": ["K"]},
    {"name": "letter$subexpression$1", "symbols": ["L"]},
    {"name": "letter$subexpression$1", "symbols": ["M"]},
    {"name": "letter$subexpression$1", "symbols": ["N"]},
    {"name": "letter$subexpression$1", "symbols": ["O"]},
    {"name": "letter$subexpression$1", "symbols": ["P"]},
    {"name": "letter$subexpression$1", "symbols": ["Q"]},
    {"name": "letter$subexpression$1", "symbols": ["R"]},
    {"name": "letter$subexpression$1", "symbols": ["S"]},
    {"name": "letter$subexpression$1", "symbols": ["T"]},
    {"name": "letter$subexpression$1", "symbols": ["U"]},
    {"name": "letter$subexpression$1", "symbols": ["V"]},
    {"name": "letter$subexpression$1", "symbols": ["W"]},
    {"name": "letter$subexpression$1", "symbols": ["X"]},
    {"name": "letter$subexpression$1", "symbols": ["Y"]},
    {"name": "letter$subexpression$1", "symbols": ["Z"]},
    {"name": "letter", "symbols": ["letter$subexpression$1"], "postprocess": id},
    {"name": "A", "symbols": [{"literal":"A"}]},
    {"name": "A", "symbols": [{"literal":"a"}]},
    {"name": "A", "symbols": [{"literal":"Ă"}]},
    {"name": "A", "symbols": [{"literal":"ă"}]},
    {"name": "A", "symbols": [{"literal":"â"}]},
    {"name": "A", "symbols": [{"literal":"Â"}]},
    {"name": "B", "symbols": [{"literal":"B"}]},
    {"name": "B", "symbols": [{"literal":"b"}]},
    {"name": "C", "symbols": [{"literal":"C"}]},
    {"name": "C", "symbols": [{"literal":"c"}]},
    {"name": "D", "symbols": [{"literal":"D"}]},
    {"name": "D", "symbols": [{"literal":"d"}]},
    {"name": "E", "symbols": [{"literal":"E"}]},
    {"name": "E", "symbols": [{"literal":"e"}]},
    {"name": "F", "symbols": [{"literal":"F"}]},
    {"name": "F", "symbols": [{"literal":"f"}]},
    {"name": "G", "symbols": [{"literal":"G"}]},
    {"name": "G", "symbols": [{"literal":"g"}]},
    {"name": "H", "symbols": [{"literal":"H"}]},
    {"name": "H", "symbols": [{"literal":"h"}]},
    {"name": "I", "symbols": [{"literal":"I"}]},
    {"name": "I", "symbols": [{"literal":"i"}]},
    {"name": "I", "symbols": [{"literal":"Î"}]},
    {"name": "I", "symbols": [{"literal":"î"}]},
    {"name": "J", "symbols": [{"literal":"J"}]},
    {"name": "J", "symbols": [{"literal":"j"}]},
    {"name": "K", "symbols": [{"literal":"K"}]},
    {"name": "K", "symbols": [{"literal":"k"}]},
    {"name": "L", "symbols": [{"literal":"L"}]},
    {"name": "L", "symbols": [{"literal":"l"}]},
    {"name": "M", "symbols": [{"literal":"M"}]},
    {"name": "M", "symbols": [{"literal":"m"}]},
    {"name": "N", "symbols": [{"literal":"N"}]},
    {"name": "N", "symbols": [{"literal":"n"}]},
    {"name": "O", "symbols": [{"literal":"O"}]},
    {"name": "O", "symbols": [{"literal":"o"}]},
    {"name": "P", "symbols": [{"literal":"P"}]},
    {"name": "P", "symbols": [{"literal":"p"}]},
    {"name": "Q", "symbols": [{"literal":"Q"}]},
    {"name": "Q", "symbols": [{"literal":"q"}]},
    {"name": "R", "symbols": [{"literal":"R"}]},
    {"name": "R", "symbols": [{"literal":"r"}]},
    {"name": "S", "symbols": [{"literal":"S"}]},
    {"name": "S", "symbols": [{"literal":"s"}]},
    {"name": "S", "symbols": [{"literal":"Ș"}]},
    {"name": "S", "symbols": [{"literal":"ș"}]},
    {"name": "T", "symbols": [{"literal":"T"}]},
    {"name": "T", "symbols": [{"literal":"t"}]},
    {"name": "T", "symbols": [{"literal":"Ț"}]},
    {"name": "T", "symbols": [{"literal":"ț"}]},
    {"name": "U", "symbols": [{"literal":"U"}]},
    {"name": "U", "symbols": [{"literal":"u"}]},
    {"name": "V", "symbols": [{"literal":"V"}]},
    {"name": "V", "symbols": [{"literal":"v"}]},
    {"name": "W", "symbols": [{"literal":"W"}]},
    {"name": "W", "symbols": [{"literal":"w"}]},
    {"name": "X", "symbols": [{"literal":"X"}]},
    {"name": "X", "symbols": [{"literal":"x"}]},
    {"name": "Y", "symbols": [{"literal":"Y"}]},
    {"name": "Y", "symbols": [{"literal":"y"}]},
    {"name": "Z", "symbols": [{"literal":"Z"}]},
    {"name": "Z", "symbols": [{"literal":"z"}]},
    {"name": "sep", "symbols": [/['.', '?', '!', ',', ';', ':', '"', '“', '”', '-', '/']/], "postprocess": () => null},
    {"name": "no$subexpression$1$ebnf$1", "symbols": []},
    {"name": "no$subexpression$1$ebnf$1$subexpression$1", "symbols": [/[1-9]/, {"literal":"."}]},
    {"name": "no$subexpression$1$ebnf$1", "symbols": ["no$subexpression$1$ebnf$1", "no$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no$subexpression$1", "symbols": ["no$subexpression$1$ebnf$1", "_"]},
    {"name": "no", "symbols": ["no$subexpression$1"], "postprocess": () => null},
    {"name": "no$ebnf$1", "symbols": []},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"I"}]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$1"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":"I"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$2"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$3", "symbols": [{"literal":"I"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$3"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"V"}]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$4", "symbols": [{"literal":"V"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$4"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$5", "symbols": [{"literal":"V"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$5"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$6", "symbols": [{"literal":"V"}, {"literal":"I"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$6"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$7", "symbols": [{"literal":"I"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$7"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"X"}]},
    {"name": "no$ebnf$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1", {"literal":"."}, "_"]},
    {"name": "no$ebnf$1", "symbols": ["no$ebnf$1", "no$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no", "symbols": ["no$ebnf$1"], "postprocess": () => null},
    {"name": "no$ebnf$2", "symbols": []},
    {"name": "no$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"a"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$1"]},
    {"name": "no$ebnf$2$subexpression$1$string$2", "symbols": [{"literal":"b"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$2"]},
    {"name": "no$ebnf$2$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$3"]},
    {"name": "no$ebnf$2$subexpression$1$string$4", "symbols": [{"literal":"d"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$4"]},
    {"name": "no$ebnf$2$subexpression$1$string$5", "symbols": [{"literal":"e"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$5"]},
    {"name": "no$ebnf$2$subexpression$1$string$6", "symbols": [{"literal":"f"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$6"]},
    {"name": "no$ebnf$2", "symbols": ["no$ebnf$2", "no$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no", "symbols": ["no$ebnf$2"], "postprocess": () => null},
    {"name": "digit", "symbols": [/[0-9]/]},
    {"name": "nume", "symbols": ["word"], "postprocess": (data) => data[0]},
    {"name": "nume$subexpression$1", "symbols": [{"literal":" "}]},
    {"name": "nume$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "nume", "symbols": ["nume", "nume$subexpression$1", "word"], "postprocess": (data) => data[0]+ data[1] + data[2]},
    {"name": "numar", "symbols": ["numarIntreg"]},
    {"name": "numar", "symbols": ["numarZecimal"]},
    {"name": "numarIntreg", "symbols": ["digit"], "postprocess": (data) => data[0]},
    {"name": "numarIntreg", "symbols": ["numarIntreg", "digit"], "postprocess": (data) => data[0]+ data[1]},
    {"name": "numarZecimal", "symbols": ["numarIntreg", {"literal":"."}, "digit", "digit"], "postprocess": (data) => data[0]+ data[1]+ data[2]},
    {"name": "nrInreg", "symbols": ["numarIntreg", {"literal":"/"}, "numarIntreg"], "postprocess": (data) => data[0] + data[1] + data[2]},
    {"name": "data", "symbols": ["zi", "sep", "luna", "sep", "an"], "postprocess": (data) => data[0] + "/" + data[2] + "/" + data[4]},
    {"name": "an", "symbols": ["digit", "digit", "digit", "digit"], "postprocess": (data) => data[0]+data[1]+data[2]+data[3]},
    {"name": "luna", "symbols": ["digit", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "zi", "symbols": ["digit", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "bloc", "symbols": ["letter"], "postprocess": (data) => data[0]},
    {"name": "bloc", "symbols": ["bloc", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ \t]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": () => null},
    {"name": "__$ebnf$1", "symbols": [/[ \t]/]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", /[ \t]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": () => null},
    {"name": "endl$ebnf$1", "symbols": []},
    {"name": "endl$ebnf$1", "symbols": ["endl$ebnf$1", /[ \r\n]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "endl", "symbols": ["endl$ebnf$1"], "postprocess": () => null},
    {"name": "_ml$ebnf$1", "symbols": []},
    {"name": "_ml$ebnf$1$subexpression$1", "symbols": [/[ \t]/]},
    {"name": "_ml$ebnf$1$subexpression$1", "symbols": [/[ \r\n]/]},
    {"name": "_ml$ebnf$1", "symbols": ["_ml$ebnf$1", "_ml$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_ml", "symbols": ["_ml$ebnf$1"]},
    {"name": "__ml$ebnf$1$subexpression$1", "symbols": [/[ \t]/]},
    {"name": "__ml$ebnf$1$subexpression$1", "symbols": [/[ \r\n]/]},
    {"name": "__ml$ebnf$1", "symbols": ["__ml$ebnf$1$subexpression$1"]},
    {"name": "__ml$ebnf$1$subexpression$2", "symbols": [/[ \t]/]},
    {"name": "__ml$ebnf$1$subexpression$2", "symbols": [/[ \r\n]/]},
    {"name": "__ml$ebnf$1", "symbols": ["__ml$ebnf$1", "__ml$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__ml", "symbols": ["__ml$ebnf$1"]},
    {"name": "__lb_$ebnf$1$subexpression$1", "symbols": ["_", /[ \r\n]/]},
    {"name": "__lb_$ebnf$1", "symbols": ["__lb_$ebnf$1$subexpression$1"]},
    {"name": "__lb_$ebnf$1$subexpression$2", "symbols": ["_", /[ \r\n]/]},
    {"name": "__lb_$ebnf$1", "symbols": ["__lb_$ebnf$1", "__lb_$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__lb_", "symbols": ["__lb_$ebnf$1", "_"]},
    {"name": "pretContract$ebnf$1$subexpression$1$subexpression$1", "symbols": [/[pP]/, /[rR]/, /[eE]/, /[țȚ]/, /[uU]/, /[lL]/, {"literal":" "}, /[cC]/, /[oO]/, /[nN]/, /[tT]/, /[rR]/, /[aA]/, /[cC]/, /[tT]/, /[uU]/, /[lL]/, /[uU]/, /[iI]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "pretContract$ebnf$1$subexpression$1", "symbols": ["pretContract$ebnf$1$subexpression$1$subexpression$1"]},
    {"name": "pretContract$ebnf$1", "symbols": ["pretContract$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "pretContract$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "pretContract$string$1", "symbols": [{"literal":"P"}, {"literal":"r"}, {"literal":"e"}, {"literal":"ț"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"v"}, {"literal":"â"}, {"literal":"n"}, {"literal":"z"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract$string$2", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"e"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract$string$3", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"i"}, {"literal":","}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"c"}, {"literal":"u"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"m"}, {"literal":"b"}, {"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"u"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract$string$4", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"i"}, {"literal":"/"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract$string$5", "symbols": [{"literal":"A"}, {"literal":"c"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":"a"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"î"}, {"literal":"n"}, {"literal":"c"}, {"literal":"a"}, {"literal":"s"}, {"literal":"a"}, {"literal":"t"}, {"literal":"ă"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"ă"}, {"literal":"r"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":" "}, {"literal":"v"}, {"literal":"â"}, {"literal":"n"}, {"literal":"z"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":","}, {"literal":" "}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"ă"}, {"literal":"z"}, {"literal":"i"}, {"literal":","}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract$string$6", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}, {"literal":"a"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"ă"}, {"literal":"r"}, {"literal":"i"}, {"literal":"i"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"z"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"l"}, {"literal":"u"}, {"literal":"i"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":","}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"b"}, {"literal":"i"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"u"}, {"literal":"l"}, {"literal":"u"}, {"literal":"i"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"ă"}, {"literal":" "}, {"literal":"î"}, {"literal":"n"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"ă"}, {"literal":"p"}, {"literal":"â"}, {"literal":"n"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"ă"}, {"literal":"r"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"u"}, {"literal":"l"}, {"literal":"u"}, {"literal":"i"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":" "}, {"literal":"ș"}, {"literal":"i"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"p"}, {"literal":"t"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pretContract", "symbols": ["no", "pretContract$ebnf$1", "_ml", "no", "pretContract$string$1", "numar", "_", "valuta", "pretContract$string$2", "numar", "pretContract$string$3", "numar", "pretContract$string$4", "valuta", {"literal":"."}, "_ml", "no", "pretContract$string$5", "data", "pretContract$string$6"], "postprocess": (data) => "Prețul contractului: " + data[5] + " " + data[7] + " (" + data[9] +" lei)"},
    {"name": "valuta$string$1", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$1"]},
    {"name": "valuta$string$2", "symbols": [{"literal":"E"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$2"]},
    {"name": "valuta", "symbols": [{"literal":"€"}]},
    {"name": "valuta$string$3", "symbols": [{"literal":"U"}, {"literal":"S"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$3"]},
    {"name": "valuta", "symbols": [{"literal":"$"}]},
    {"name": "valuta$string$4", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$4"]},
    {"name": "valuta$string$5", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$5"]},
    {"name": "valuta$string$6", "symbols": [{"literal":"G"}, {"literal":"B"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "valuta", "symbols": ["valuta$string$6"]},
    {"name": "valuta", "symbols": [{"literal":"£"}], "postprocess": id}
]
  , ParserStart: "pretContract"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
