// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "text$subexpression$1$ebnf$1", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$1", "symbols": ["word", "text$subexpression$1$ebnf$1", "_"]},
    {"name": "text$subexpression$1$ebnf$2", "symbols": ["digit"]},
    {"name": "text$subexpression$1$ebnf$2", "symbols": ["text$subexpression$1$ebnf$2", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "text$subexpression$1$ebnf$3", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$1", "symbols": ["text$subexpression$1$ebnf$2", "text$subexpression$1$ebnf$3", "_"]},
    {"name": "text", "symbols": ["text$subexpression$1"]},
    {"name": "text$subexpression$2$ebnf$1", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$2", "symbols": ["word", "text$subexpression$2$ebnf$1", "_"]},
    {"name": "text$subexpression$2$ebnf$2", "symbols": ["digit"]},
    {"name": "text$subexpression$2$ebnf$2", "symbols": ["text$subexpression$2$ebnf$2", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "text$subexpression$2$ebnf$3", "symbols": ["sep"], "postprocess": id},
    {"name": "text$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "text$subexpression$2", "symbols": ["text$subexpression$2$ebnf$2", "text$subexpression$2$ebnf$3", "_"]},
    {"name": "text", "symbols": ["text", "text$subexpression$2"]},
    {"name": "words$ebnf$1", "symbols": ["word"]},
    {"name": "words$ebnf$1", "symbols": ["words$ebnf$1", "word"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "words", "symbols": ["words$ebnf$1"]},
    {"name": "word$ebnf$1", "symbols": ["letter"]},
    {"name": "word$ebnf$1", "symbols": ["word$ebnf$1", "letter"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "word", "symbols": ["word$ebnf$1"], "postprocess": (data) => data[0].join('')},
    {"name": "letter$subexpression$1", "symbols": ["A"]},
    {"name": "letter$subexpression$1", "symbols": ["B"]},
    {"name": "letter$subexpression$1", "symbols": ["C"]},
    {"name": "letter$subexpression$1", "symbols": ["D"]},
    {"name": "letter$subexpression$1", "symbols": ["E"]},
    {"name": "letter$subexpression$1", "symbols": ["F"]},
    {"name": "letter$subexpression$1", "symbols": ["G"]},
    {"name": "letter$subexpression$1", "symbols": ["H"]},
    {"name": "letter$subexpression$1", "symbols": ["I"]},
    {"name": "letter$subexpression$1", "symbols": ["J"]},
    {"name": "letter$subexpression$1", "symbols": ["K"]},
    {"name": "letter$subexpression$1", "symbols": ["L"]},
    {"name": "letter$subexpression$1", "symbols": ["M"]},
    {"name": "letter$subexpression$1", "symbols": ["N"]},
    {"name": "letter$subexpression$1", "symbols": ["O"]},
    {"name": "letter$subexpression$1", "symbols": ["P"]},
    {"name": "letter$subexpression$1", "symbols": ["Q"]},
    {"name": "letter$subexpression$1", "symbols": ["R"]},
    {"name": "letter$subexpression$1", "symbols": ["S"]},
    {"name": "letter$subexpression$1", "symbols": ["T"]},
    {"name": "letter$subexpression$1", "symbols": ["U"]},
    {"name": "letter$subexpression$1", "symbols": ["V"]},
    {"name": "letter$subexpression$1", "symbols": ["W"]},
    {"name": "letter$subexpression$1", "symbols": ["X"]},
    {"name": "letter$subexpression$1", "symbols": ["Y"]},
    {"name": "letter$subexpression$1", "symbols": ["Z"]},
    {"name": "letter", "symbols": ["letter$subexpression$1"], "postprocess": id},
    {"name": "A", "symbols": [{"literal":"A"}]},
    {"name": "A", "symbols": [{"literal":"a"}]},
    {"name": "A", "symbols": [{"literal":"Ă"}]},
    {"name": "A", "symbols": [{"literal":"ă"}]},
    {"name": "A", "symbols": [{"literal":"â"}]},
    {"name": "A", "symbols": [{"literal":"Â"}]},
    {"name": "B", "symbols": [{"literal":"B"}]},
    {"name": "B", "symbols": [{"literal":"b"}]},
    {"name": "C", "symbols": [{"literal":"C"}]},
    {"name": "C", "symbols": [{"literal":"c"}]},
    {"name": "D", "symbols": [{"literal":"D"}]},
    {"name": "D", "symbols": [{"literal":"d"}]},
    {"name": "E", "symbols": [{"literal":"E"}]},
    {"name": "E", "symbols": [{"literal":"e"}]},
    {"name": "F", "symbols": [{"literal":"F"}]},
    {"name": "F", "symbols": [{"literal":"f"}]},
    {"name": "G", "symbols": [{"literal":"G"}]},
    {"name": "G", "symbols": [{"literal":"g"}]},
    {"name": "H", "symbols": [{"literal":"H"}]},
    {"name": "H", "symbols": [{"literal":"h"}]},
    {"name": "I", "symbols": [{"literal":"I"}]},
    {"name": "I", "symbols": [{"literal":"i"}]},
    {"name": "I", "symbols": [{"literal":"Î"}]},
    {"name": "I", "symbols": [{"literal":"î"}]},
    {"name": "J", "symbols": [{"literal":"J"}]},
    {"name": "J", "symbols": [{"literal":"j"}]},
    {"name": "K", "symbols": [{"literal":"K"}]},
    {"name": "K", "symbols": [{"literal":"k"}]},
    {"name": "L", "symbols": [{"literal":"L"}]},
    {"name": "L", "symbols": [{"literal":"l"}]},
    {"name": "M", "symbols": [{"literal":"M"}]},
    {"name": "M", "symbols": [{"literal":"m"}]},
    {"name": "N", "symbols": [{"literal":"N"}]},
    {"name": "N", "symbols": [{"literal":"n"}]},
    {"name": "O", "symbols": [{"literal":"O"}]},
    {"name": "O", "symbols": [{"literal":"o"}]},
    {"name": "P", "symbols": [{"literal":"P"}]},
    {"name": "P", "symbols": [{"literal":"p"}]},
    {"name": "Q", "symbols": [{"literal":"Q"}]},
    {"name": "Q", "symbols": [{"literal":"q"}]},
    {"name": "R", "symbols": [{"literal":"R"}]},
    {"name": "R", "symbols": [{"literal":"r"}]},
    {"name": "S", "symbols": [{"literal":"S"}]},
    {"name": "S", "symbols": [{"literal":"s"}]},
    {"name": "S", "symbols": [{"literal":"Ș"}]},
    {"name": "S", "symbols": [{"literal":"ș"}]},
    {"name": "T", "symbols": [{"literal":"T"}]},
    {"name": "T", "symbols": [{"literal":"t"}]},
    {"name": "T", "symbols": [{"literal":"Ț"}]},
    {"name": "T", "symbols": [{"literal":"ț"}]},
    {"name": "U", "symbols": [{"literal":"U"}]},
    {"name": "U", "symbols": [{"literal":"u"}]},
    {"name": "V", "symbols": [{"literal":"V"}]},
    {"name": "V", "symbols": [{"literal":"v"}]},
    {"name": "W", "symbols": [{"literal":"W"}]},
    {"name": "W", "symbols": [{"literal":"w"}]},
    {"name": "X", "symbols": [{"literal":"X"}]},
    {"name": "X", "symbols": [{"literal":"x"}]},
    {"name": "Y", "symbols": [{"literal":"Y"}]},
    {"name": "Y", "symbols": [{"literal":"y"}]},
    {"name": "Z", "symbols": [{"literal":"Z"}]},
    {"name": "Z", "symbols": [{"literal":"z"}]},
    {"name": "sep", "symbols": [/['.', '?', '!', ',', ';', ':', '"', '“', '”', '-', '/']/], "postprocess": () => null},
    {"name": "no$subexpression$1$ebnf$1", "symbols": []},
    {"name": "no$subexpression$1$ebnf$1$subexpression$1", "symbols": [/[1-9]/, {"literal":"."}]},
    {"name": "no$subexpression$1$ebnf$1", "symbols": ["no$subexpression$1$ebnf$1", "no$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no$subexpression$1", "symbols": ["no$subexpression$1$ebnf$1", "_"]},
    {"name": "no", "symbols": ["no$subexpression$1"], "postprocess": () => null},
    {"name": "no$ebnf$1", "symbols": []},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"I"}]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$1"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":"I"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$2"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$3", "symbols": [{"literal":"I"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$3"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"V"}]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$4", "symbols": [{"literal":"V"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$4"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$5", "symbols": [{"literal":"V"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$5"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$6", "symbols": [{"literal":"V"}, {"literal":"I"}, {"literal":"I"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$6"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1$string$7", "symbols": [{"literal":"I"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1$string$7"]},
    {"name": "no$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"X"}]},
    {"name": "no$ebnf$1$subexpression$1", "symbols": ["no$ebnf$1$subexpression$1$subexpression$1", {"literal":"."}, "_"]},
    {"name": "no$ebnf$1", "symbols": ["no$ebnf$1", "no$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no", "symbols": ["no$ebnf$1"], "postprocess": () => null},
    {"name": "no$ebnf$2", "symbols": []},
    {"name": "no$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"a"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$1"]},
    {"name": "no$ebnf$2$subexpression$1$string$2", "symbols": [{"literal":"b"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$2"]},
    {"name": "no$ebnf$2$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$3"]},
    {"name": "no$ebnf$2$subexpression$1$string$4", "symbols": [{"literal":"d"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$4"]},
    {"name": "no$ebnf$2$subexpression$1$string$5", "symbols": [{"literal":"e"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$5"]},
    {"name": "no$ebnf$2$subexpression$1$string$6", "symbols": [{"literal":"f"}, {"literal":")"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "no$ebnf$2$subexpression$1", "symbols": ["no$ebnf$2$subexpression$1$string$6"]},
    {"name": "no$ebnf$2", "symbols": ["no$ebnf$2", "no$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "no", "symbols": ["no$ebnf$2"], "postprocess": () => null},
    {"name": "digit", "symbols": [/[0-9]/]},
    {"name": "nume", "symbols": ["word"], "postprocess": (data) => data[0]},
    {"name": "nume$subexpression$1", "symbols": [{"literal":" "}]},
    {"name": "nume$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "nume", "symbols": ["nume", "nume$subexpression$1", "word"], "postprocess": (data) => data[0]+ data[1] + data[2]},
    {"name": "numar", "symbols": ["numarIntreg"]},
    {"name": "numar", "symbols": ["numarZecimal"]},
    {"name": "numarIntreg", "symbols": ["digit"], "postprocess": (data) => data[0]},
    {"name": "numarIntreg", "symbols": ["numarIntreg", "digit"], "postprocess": (data) => data[0]+ data[1]},
    {"name": "numarZecimal", "symbols": ["numarIntreg", {"literal":"."}, "digit", "digit"], "postprocess": (data) => data[0]+ data[1]+ data[2]},
    {"name": "nrInreg", "symbols": ["numarIntreg", {"literal":"/"}, "numarIntreg"], "postprocess": (data) => data[0] + data[1] + data[2]},
    {"name": "data", "symbols": ["zi", "sep", "luna", "sep", "an"], "postprocess": (data) => data[0] + "/" + data[2] + "/" + data[4]},
    {"name": "an", "symbols": ["digit", "digit", "digit", "digit"], "postprocess": (data) => data[0]+data[1]+data[2]+data[3]},
    {"name": "luna", "symbols": ["digit", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "zi", "symbols": ["digit", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "bloc", "symbols": ["letter"], "postprocess": (data) => data[0]},
    {"name": "bloc", "symbols": ["bloc", "digit"], "postprocess": (data) => data[0]+data[1]},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ \t]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": () => null},
    {"name": "__$ebnf$1", "symbols": [/[ \t]/]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", /[ \t]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": () => null},
    {"name": "endl$ebnf$1", "symbols": []},
    {"name": "endl$ebnf$1", "symbols": ["endl$ebnf$1", /[ \r\n]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "endl", "symbols": ["endl$ebnf$1"], "postprocess": () => null},
    {"name": "_ml$ebnf$1", "symbols": []},
    {"name": "_ml$ebnf$1$subexpression$1", "symbols": [/[ \t]/]},
    {"name": "_ml$ebnf$1$subexpression$1", "symbols": [/[ \r\n]/]},
    {"name": "_ml$ebnf$1", "symbols": ["_ml$ebnf$1", "_ml$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_ml", "symbols": ["_ml$ebnf$1"]},
    {"name": "__ml$ebnf$1$subexpression$1", "symbols": [/[ \t]/]},
    {"name": "__ml$ebnf$1$subexpression$1", "symbols": [/[ \r\n]/]},
    {"name": "__ml$ebnf$1", "symbols": ["__ml$ebnf$1$subexpression$1"]},
    {"name": "__ml$ebnf$1$subexpression$2", "symbols": [/[ \t]/]},
    {"name": "__ml$ebnf$1$subexpression$2", "symbols": [/[ \r\n]/]},
    {"name": "__ml$ebnf$1", "symbols": ["__ml$ebnf$1", "__ml$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__ml", "symbols": ["__ml$ebnf$1"]},
    {"name": "__lb_$ebnf$1$subexpression$1", "symbols": ["_", /[ \r\n]/]},
    {"name": "__lb_$ebnf$1", "symbols": ["__lb_$ebnf$1$subexpression$1"]},
    {"name": "__lb_$ebnf$1$subexpression$2", "symbols": ["_", /[ \r\n]/]},
    {"name": "__lb_$ebnf$1", "symbols": ["__lb_$ebnf$1", "__lb_$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__lb_", "symbols": ["__lb_$ebnf$1", "_"]},
    {"name": "contractanti$subexpression$1$string$1", "symbols": [{"literal":"P"}, {"literal":"ă"}, {"literal":"r"}, {"literal":"ț"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contractanti$subexpression$1", "symbols": ["contractanti$subexpression$1$string$1"]},
    {"name": "contractanti$subexpression$1$string$2", "symbols": [{"literal":"Î"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contractanti$subexpression$1", "symbols": ["contractanti$subexpression$1$string$2"]},
    {"name": "contractanti$subexpression$1$string$3", "symbols": [{"literal":"Î"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"s"}, {"literal":"e"}, {"literal":"m"}, {"literal":"n"}, {"literal":"a"}, {"literal":"ț"}, {"literal":"i"}, {"literal":"i"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contractanti$subexpression$1", "symbols": ["contractanti$subexpression$1$string$3"]},
    {"name": "contractanti$string$1", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"ă"}, {"literal":" "}, {"literal":"î"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"z"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":" "}, {"literal":"u"}, {"literal":"r"}, {"literal":"m"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"l"}, {"literal":"a"}, {"literal":"u"}, {"literal":"z"}, {"literal":"e"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "contractanti", "symbols": ["no", "contractanti$subexpression$1", "_ml", "contractant", "contractant", "contractanti$string$1", "_ml"], "postprocess": (data) => "Contractanti: " + data[3] + ", " + data[4]},
    {"name": "contractant$ebnf$1", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "contractant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contractant", "symbols": ["no", "numeContractant", {"literal":","}, "_", "cetatenie", {"literal":","}, "_", "adresa", {"literal":","}, "_", "carteIdentitate", {"literal":","}, "_", "cnp", {"literal":","}, "_", "calitate", "contractant$ebnf$1", "_ml"], "postprocess": (data) => data[1]},
    {"name": "numeContractant", "symbols": ["nume"]},
    {"name": "cetatenie$string$1", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"t"}, {"literal":"ă"}, {"literal":"ț"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "cetatenie", "symbols": ["cetatenie$string$1", "_", "word"]},
    {"name": "adresa$subexpression$1$string$1", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"u"}, {"literal":"l"}, {"literal":" "}, {"literal":"î"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$subexpression$1", "symbols": ["adresa$subexpression$1$string$1"]},
    {"name": "adresa$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"î"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$subexpression$1", "symbols": ["adresa$subexpression$1$string$2"]},
    {"name": "adresa$subexpression$2$subexpression$1", "symbols": [/[sS]/, /[tT]/, /[rR]/, /[aA]/, /[dD]/, /[aA]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$1"]},
    {"name": "adresa$subexpression$2$subexpression$2", "symbols": [/[bB]/, /[uU]/, /[lL]/, /[eE]/, /[vV]/, /[aA]/, /[rR]/, /[dD]/, /[uU]/, /[lL]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$2"]},
    {"name": "adresa$subexpression$2$subexpression$3", "symbols": [/[șȘ]/, /[oO]/, /[sS]/, /[eE]/, /[aA]/, /[uU]/, /[aA]/], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$3"]},
    {"name": "adresa$subexpression$2$subexpression$4", "symbols": [/[sS]/, /[tT]/, /[rR]/, {"literal":"."}], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$4"]},
    {"name": "adresa$subexpression$2$subexpression$5", "symbols": [/[șȘ]/, /[oO]/, /[sS]/, {"literal":"."}], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$5"]},
    {"name": "adresa$subexpression$2$subexpression$6", "symbols": [/[bB]/, /[vV]/, /[dD]/, {"literal":"."}], "postprocess": function(d) {return d.join(""); }},
    {"name": "adresa$subexpression$2", "symbols": ["adresa$subexpression$2$subexpression$6"]},
    {"name": "adresa$string$1", "symbols": [{"literal":"n"}, {"literal":"r"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$ebnf$1$subexpression$1$string$2", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$ebnf$1$subexpression$1$string$3", "symbols": [{"literal":"e"}, {"literal":"t"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$ebnf$1$subexpression$1$string$4", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adresa$ebnf$1$subexpression$1", "symbols": [{"literal":","}, "_", "adresa$ebnf$1$subexpression$1$string$1", "_", "bloc", {"literal":","}, "_", "adresa$ebnf$1$subexpression$1$string$2", "_", "letter", {"literal":","}, "_", "adresa$ebnf$1$subexpression$1$string$3", "_", "numar", {"literal":","}, "_", "adresa$ebnf$1$subexpression$1$string$4", "_", "numar"]},
    {"name": "adresa$ebnf$1", "symbols": ["adresa$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "adresa$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "adresa", "symbols": ["adresa$subexpression$1", "nume", {"literal":","}, "_", "adresa$subexpression$2", "_", "nume", "_", "adresa$string$1", "_", "numar", "adresa$ebnf$1"], "postprocess": () => null},
    {"name": "cnp$ebnf$1$string$1", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "cnp$ebnf$1", "symbols": ["cnp$ebnf$1$string$1"], "postprocess": id},
    {"name": "cnp$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "cnp$string$1", "symbols": [{"literal":"C"}, {"literal":"N"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "cnp", "symbols": ["cnp$ebnf$1", "cnp$string$1", "_", "numar"]},
    {"name": "carteIdentitate$subexpression$1$string$1", "symbols": [{"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$subexpression$1", "symbols": ["carteIdentitate$subexpression$1$string$1"]},
    {"name": "carteIdentitate$subexpression$1$string$2", "symbols": [{"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"ă"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$subexpression$1", "symbols": ["carteIdentitate$subexpression$1$string$2"]},
    {"name": "carteIdentitate$string$1", "symbols": [{"literal":" "}, {"literal":"C"}, {"literal":"I"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$ebnf$1", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "carteIdentitate$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "carteIdentitate$string$2", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"r"}, {"literal":"."}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$ebnf$2", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "carteIdentitate$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "carteIdentitate$string$3", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"ă"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"S"}, {"literal":"P"}, {"literal":"C"}, {"literal":"E"}, {"literal":"P"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$subexpression$2", "symbols": ["nume"]},
    {"name": "carteIdentitate$subexpression$2", "symbols": ["nume", "numar"]},
    {"name": "carteIdentitate$ebnf$3", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "carteIdentitate$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "carteIdentitate$string$4", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate$string$5", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"b"}, {"literal":"i"}, {"literal":"l"}, {"literal":"ă"}, {"literal":" "}, {"literal":"p"}, {"literal":"â"}, {"literal":"n"}, {"literal":"ă"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carteIdentitate", "symbols": ["carteIdentitate$subexpression$1", "carteIdentitate$string$1", "letter", "letter", "carteIdentitate$ebnf$1", "carteIdentitate$string$2", "numar", "carteIdentitate$ebnf$2", "carteIdentitate$string$3", "carteIdentitate$subexpression$2", "carteIdentitate$ebnf$3", "carteIdentitate$string$4", "data", "carteIdentitate$string$5", "data"]},
    {"name": "calitate$ebnf$1$string$1", "symbols": [{"literal":"î"}, {"literal":"n"}, {"literal":" "}, {"literal":"n"}, {"literal":"u"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"u"}, {"literal":","}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$ebnf$1", "symbols": ["calitate$ebnf$1$string$1"], "postprocess": id},
    {"name": "calitate$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "calitate$string$1", "symbols": [{"literal":"î"}, {"literal":"n"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1$string$1", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"ă"}, {"literal":"r"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$1"]},
    {"name": "calitate$subexpression$1$string$2", "symbols": [{"literal":"v"}, {"literal":"â"}, {"literal":"n"}, {"literal":"z"}, {"literal":"ă"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$2"]},
    {"name": "calitate$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"s"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"m"}, {"literal":"b"}, {"literal":"a"}, {"literal":"ș"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$3"]},
    {"name": "calitate$subexpression$1$string$4", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"m"}, {"literal":"u"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$4"]},
    {"name": "calitate$subexpression$1$string$5", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"m"}, {"literal":"u"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$5"]},
    {"name": "calitate$subexpression$1$string$6", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$6"]},
    {"name": "calitate$subexpression$1$string$7", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calitate$subexpression$1", "symbols": ["calitate$subexpression$1$string$7"]},
    {"name": "calitate", "symbols": ["calitate$ebnf$1", "calitate$string$1", "calitate$subexpression$1"]}
]
  , ParserStart: "contractanti"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
